name: CD Trigger Tagged Environment Workflow

on:
  push:
    tags:
      - 'test-*'
      - 'prod-*'
      - 'client*-*-(test|prod)-*'

jobs:
  deploy-tagged:
    runs-on: ubuntu-latest
    steps:
      - name: Parse tag and extract config path
        id: extract
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"

          # Expecting tags like: client1-azure-test-v1
          IFS='-' read -r CLIENT CLOUD ENVIRONMENT _ <<< "$TAG_NAME"

          if [[ -z "$CLIENT" || -z "$CLOUD" || -z "$ENVIRONMENT" ]]; then
            echo "Invalid tag format. Must be: <client>-<cloud>-<env>-<version>"
            exit 1
          fi

          CONFIG_PATH="$CLIENT/$CLOUD/$ENVIRONMENT"
          echo "config_path=$CONFIG_PATH" >> $GITHUB_OUTPUT

      - name: Trigger CD Apply
        uses: sasidaren-coder/github-actions-test/.github/workflows/cd-workflow.yaml@main
        with:
          tf_action: "apply"
          config_path: ${{ steps.extract.outputs.config_path }}
