# on:
#   pull_request:
#     paths:
#       - '**/resources.yaml'

# jobs:
#   call-plan:
#     uses: sasidaren-coder/github-actions-test/.github/workflows/ci-workflow.yaml@main
#     with:
#       tf_action: "plan"
#       config_path: "client1/azure/dev"


name: CI Trigger Workflow

on:
  pull_request:
    paths:
      - '**/resources.yaml'

jobs:
  detect-config-path:
    runs-on: ubuntu-latest
    outputs:
      config_path: ${{ steps.detect-path.outputs.config_path }}
    steps:
      - name: Checkout config-repo
        uses: actions/checkout@v3

      - name: Set matrix from changed resources.yaml paths
        id: set-matrix
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "Finding changed resources.yaml files..."
          
          PATHS=$(git diff --name-only origin/${{ github.base_ref }} | grep 'resources.yaml' | xargs -n1 dirname | sort | uniq)
          
          echo "Detected paths:"
          echo "$PATHS"

          JSON_ARRAY=$(printf '%s\n' $PATHS | jq -R . | jq -s .)
          echo "Matrix JSON:"
          echo "$JSON_ARRAY"
          echo "matrix={\"config_paths\": $JSON_ARRAY}" >> $GITHUB_OUTPUT

  run-ci-per-path:
    needs: detect-changed-paths
    strategy:
      matrix:
        config_paths: ${{ fromJson(needs.detect-changed-paths.outputs.matrix).config_paths }}
    uses: sasidaren-coder/github-actions-test/.github/workflows/ci-workflow.yaml@main
    with:
      tf_action: "plan"
      config_path: ${{ matrix.config_paths }}